
-- ----------------------------
-- Table structure for tblCountryAbbr
-- ----------------------------
DROP TABLE IF EXISTS `tblCountryAbbr`;
CREATE TABLE `tblCountryAbbr` (
  `Abbr` varchar(10) NOT NULL DEFAULT '',
  `Country` varchar(200) NOT NULL DEFAULT '',
  `Cname` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`Abbr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of tblCountryAbbr
-- ----------------------------
INSERT INTO `tblCountryAbbr` VALUES ('AD', 'Andorra', '安道尔共和国');
INSERT INTO `tblCountryAbbr` VALUES ('AE', 'United Arab Emirates', '阿拉伯联合酋长国');
INSERT INTO `tblCountryAbbr` VALUES ('AF', 'Afghanistan', '阿富汗');
INSERT INTO `tblCountryAbbr` VALUES ('AG', 'Antigua and Barbuda', '安提瓜和巴布达');
INSERT INTO `tblCountryAbbr` VALUES ('AI', 'Anguilla', '安圭拉岛');
INSERT INTO `tblCountryAbbr` VALUES ('AL', 'Albania', '阿尔巴尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('AM', 'Armenia', '亚美尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('AO', 'Angola', '安哥拉');
INSERT INTO `tblCountryAbbr` VALUES ('AQ', 'Antarctica', '南极洲');
INSERT INTO `tblCountryAbbr` VALUES ('AR', 'Argentina', '阿根廷');
INSERT INTO `tblCountryAbbr` VALUES ('AS', 'American Soamoa', '美属萨摩亚');
INSERT INTO `tblCountryAbbr` VALUES ('AT', 'Austria', '奥地利');
INSERT INTO `tblCountryAbbr` VALUES ('AU', 'Australia', '澳大利亚');
INSERT INTO `tblCountryAbbr` VALUES ('AW', 'Aruba', '阿鲁巴岛');
INSERT INTO `tblCountryAbbr` VALUES ('AX', 'Aland Islands', '奥兰群岛');
INSERT INTO `tblCountryAbbr` VALUES ('AZ', 'Azerbaijan', '阿塞拜疆');
INSERT INTO `tblCountryAbbr` VALUES ('BA', 'Bosnia And Herzegovina', '波斯尼亚和黑塞哥维那');
INSERT INTO `tblCountryAbbr` VALUES ('BB', 'Barbados', '巴巴多斯');
INSERT INTO `tblCountryAbbr` VALUES ('BD', 'Bangladesh', '孟加拉国');
INSERT INTO `tblCountryAbbr` VALUES ('BE', 'Belgium', '比利时');
INSERT INTO `tblCountryAbbr` VALUES ('BF', 'Burkina-faso', '布基纳法索');
INSERT INTO `tblCountryAbbr` VALUES ('BG', 'Bulgaria', '保加利亚');
INSERT INTO `tblCountryAbbr` VALUES ('BH', 'Bahrain', '巴林');
INSERT INTO `tblCountryAbbr` VALUES ('BI', 'Burundi', '布隆迪');
INSERT INTO `tblCountryAbbr` VALUES ('BJ', 'Benin', '贝宁');
INSERT INTO `tblCountryAbbr` VALUES ('BL', 'Palestine', '巴勒斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('BM', 'Bermuda Is.', '百慕大群岛');
INSERT INTO `tblCountryAbbr` VALUES ('BN', 'Brunei', '文莱');
INSERT INTO `tblCountryAbbr` VALUES ('BO', 'Bolivia', '玻利维亚');
INSERT INTO `tblCountryAbbr` VALUES ('BQ', 'Bonaire, Saint Eustatius And Saba', '博内尔岛，圣尤斯特歇斯和萨巴');
INSERT INTO `tblCountryAbbr` VALUES ('BR', 'Brazil', '巴西');
INSERT INTO `tblCountryAbbr` VALUES ('BS', 'Bahamas', '巴哈马');
INSERT INTO `tblCountryAbbr` VALUES ('BT', 'Bhutan', '不丹');
INSERT INTO `tblCountryAbbr` VALUES ('BV', 'Bouvet Island', '布维岛');
INSERT INTO `tblCountryAbbr` VALUES ('BW', 'Botswana', '博茨瓦纳');
INSERT INTO `tblCountryAbbr` VALUES ('BY', 'Belarus', '白俄罗斯');
INSERT INTO `tblCountryAbbr` VALUES ('BZ', 'Belize', '伯利兹');
INSERT INTO `tblCountryAbbr` VALUES ('CA', 'Canada', '加拿大');
INSERT INTO `tblCountryAbbr` VALUES ('CC', 'Cocos (Keeling) Islands', '科科斯群岛');
INSERT INTO `tblCountryAbbr` VALUES ('CD', 'Congo, The Democratic Republic', '刚果民主共和国');
INSERT INTO `tblCountryAbbr` VALUES ('CF', 'Central African Republic', '中非共和国');
INSERT INTO `tblCountryAbbr` VALUES ('CG', 'Congo', '刚果');
INSERT INTO `tblCountryAbbr` VALUES ('CH', 'Switzerland', '瑞士');
INSERT INTO `tblCountryAbbr` VALUES ('CI', 'Cote D\'ivoire', '科特迪瓦');
INSERT INTO `tblCountryAbbr` VALUES ('CK', 'Cook Is.', '库克群岛');
INSERT INTO `tblCountryAbbr` VALUES ('CL', 'Chile', '智利');
INSERT INTO `tblCountryAbbr` VALUES ('CM', 'Cameroon', '喀麦隆');
INSERT INTO `tblCountryAbbr` VALUES ('CN', 'China', '中国');
INSERT INTO `tblCountryAbbr` VALUES ('CO', 'Colombia', '哥伦比亚');
INSERT INTO `tblCountryAbbr` VALUES ('CR', 'Costa Rica', '哥斯达黎加');
INSERT INTO `tblCountryAbbr` VALUES ('CU', 'Cuba', '古巴');
INSERT INTO `tblCountryAbbr` VALUES ('CV', 'Cape Verde', '佛得角');
INSERT INTO `tblCountryAbbr` VALUES ('CW', 'Curacao', '库拉索');
INSERT INTO `tblCountryAbbr` VALUES ('CX', 'Christmas Island', '圣诞岛');
INSERT INTO `tblCountryAbbr` VALUES ('CY', 'Cyprus', '塞浦路斯');
INSERT INTO `tblCountryAbbr` VALUES ('CZ', 'Czech Republic', '捷克');
INSERT INTO `tblCountryAbbr` VALUES ('DE', 'Germany', '德国');
INSERT INTO `tblCountryAbbr` VALUES ('DJ', 'Djibouti', '吉布提');
INSERT INTO `tblCountryAbbr` VALUES ('DK', 'Denmark', '丹麦');
INSERT INTO `tblCountryAbbr` VALUES ('DM', 'Dominica', '多米尼加');
INSERT INTO `tblCountryAbbr` VALUES ('DO', 'Dominica Rep.', '多米尼加共和国');
INSERT INTO `tblCountryAbbr` VALUES ('DZ', 'Algeria', '阿尔及利亚');
INSERT INTO `tblCountryAbbr` VALUES ('EC', 'Ecuador', '厄瓜多尔');
INSERT INTO `tblCountryAbbr` VALUES ('EE', 'Estonia', '爱沙尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('EG', 'Egypt', '埃及');
INSERT INTO `tblCountryAbbr` VALUES ('EH', 'Western Sahara', '西撒哈拉');
INSERT INTO `tblCountryAbbr` VALUES ('ER', 'Eritrea', '厄立特里亚');
INSERT INTO `tblCountryAbbr` VALUES ('ES', 'Spain', '西班牙');
INSERT INTO `tblCountryAbbr` VALUES ('ET', 'Ethiopia', '埃塞俄比亚');
INSERT INTO `tblCountryAbbr` VALUES ('FI', 'Finland', '芬兰');
INSERT INTO `tblCountryAbbr` VALUES ('FJ', 'Fiji', '斐济');
INSERT INTO `tblCountryAbbr` VALUES ('FK', 'Falkland Islands (Malvinas)', '福克兰群岛（马尔维纳斯群岛）');
INSERT INTO `tblCountryAbbr` VALUES ('FM', 'Federated States of Micronesia', '密克罗尼西亚联邦');
INSERT INTO `tblCountryAbbr` VALUES ('FO', 'Faroe Islands', '法罗群岛');
INSERT INTO `tblCountryAbbr` VALUES ('FR', 'France', '法国');
INSERT INTO `tblCountryAbbr` VALUES ('GA', 'Gabon', '加蓬');
INSERT INTO `tblCountryAbbr` VALUES ('GB', 'United Kiongdom', '英国');
INSERT INTO `tblCountryAbbr` VALUES ('GD', 'Grenada', '格林纳达');
INSERT INTO `tblCountryAbbr` VALUES ('GE', 'Georgia', '格鲁吉亚');
INSERT INTO `tblCountryAbbr` VALUES ('GF', 'French Guiana', '法属圭亚那');
INSERT INTO `tblCountryAbbr` VALUES ('GG', 'Guernsey', '根西岛');
INSERT INTO `tblCountryAbbr` VALUES ('GH', 'Ghana', '加纳');
INSERT INTO `tblCountryAbbr` VALUES ('GI', 'Gibraltar', '直布罗陀');
INSERT INTO `tblCountryAbbr` VALUES ('GL', 'Greenland', '格陵兰');
INSERT INTO `tblCountryAbbr` VALUES ('GM', 'Gambia', '冈比亚');
INSERT INTO `tblCountryAbbr` VALUES ('GN', 'Guinea', '几内亚');
INSERT INTO `tblCountryAbbr` VALUES ('GP', 'Guadeloupe', '瓜德罗普岛');
INSERT INTO `tblCountryAbbr` VALUES ('GQ', 'Equatorial Guinea', '赤道几内亚');
INSERT INTO `tblCountryAbbr` VALUES ('GR', 'Greece', '希腊');
INSERT INTO `tblCountryAbbr` VALUES ('GS', 'South Georgia and the South Sandwich Islands', '南乔治亚岛和南桑威奇群岛');
INSERT INTO `tblCountryAbbr` VALUES ('GT', 'Guatemala', '危地马拉');
INSERT INTO `tblCountryAbbr` VALUES ('GU', 'Guam', '关岛');
INSERT INTO `tblCountryAbbr` VALUES ('GW', 'Guinea-bissau', '几内亚比绍');
INSERT INTO `tblCountryAbbr` VALUES ('GY', 'Guyana', '圭亚那');
INSERT INTO `tblCountryAbbr` VALUES ('HK', 'Hongkong', '香港特别行政区');
INSERT INTO `tblCountryAbbr` VALUES ('HM', 'Heard Island and McDonald Islands', '赫德岛和麦当劳群岛');
INSERT INTO `tblCountryAbbr` VALUES ('HN', 'Honduras', '洪都拉斯');
INSERT INTO `tblCountryAbbr` VALUES ('HR', 'Croatia', '克罗地亚');
INSERT INTO `tblCountryAbbr` VALUES ('HT', 'Haiti', '海地');
INSERT INTO `tblCountryAbbr` VALUES ('HU', 'Hungary', '匈牙利');
INSERT INTO `tblCountryAbbr` VALUES ('ID', 'Indonesia', '印度尼西亚');
INSERT INTO `tblCountryAbbr` VALUES ('IE', 'Ireland', '爱尔兰');
INSERT INTO `tblCountryAbbr` VALUES ('IL', 'Israel', '以色列');
INSERT INTO `tblCountryAbbr` VALUES ('IM', 'Isle Of Man', '马恩岛');
INSERT INTO `tblCountryAbbr` VALUES ('IN', 'India', '印度');
INSERT INTO `tblCountryAbbr` VALUES ('IO', 'British Indian Ocean Territory', '英属印度洋领地');
INSERT INTO `tblCountryAbbr` VALUES ('IQ', 'Iraq', '伊拉克');
INSERT INTO `tblCountryAbbr` VALUES ('IR', 'Iran', '伊朗');
INSERT INTO `tblCountryAbbr` VALUES ('IS', 'Iceland', '冰岛');
INSERT INTO `tblCountryAbbr` VALUES ('IT', 'Italy', '意大利');
INSERT INTO `tblCountryAbbr` VALUES ('JE', 'Jersey', '泽西岛');
INSERT INTO `tblCountryAbbr` VALUES ('JM', 'Jamaica', '牙买加');
INSERT INTO `tblCountryAbbr` VALUES ('JO', 'Jordan', '约旦');
INSERT INTO `tblCountryAbbr` VALUES ('JP', 'Japan', '日本');
INSERT INTO `tblCountryAbbr` VALUES ('KE', 'Kenya', '肯尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('KG', 'Kyrgyzstan', '吉尔吉斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('KH', 'Kampuchea (Cambodia )', '柬埔寨');
INSERT INTO `tblCountryAbbr` VALUES ('KI', 'Kiribati', '基里巴斯');
INSERT INTO `tblCountryAbbr` VALUES ('KM', 'Comoros', '科摩罗');
INSERT INTO `tblCountryAbbr` VALUES ('KN', 'Saint Kitts And Nevis', '圣基茨和尼维斯');
INSERT INTO `tblCountryAbbr` VALUES ('KP', 'North Korea', '朝鲜');
INSERT INTO `tblCountryAbbr` VALUES ('KR', 'Korea', '韩国');
INSERT INTO `tblCountryAbbr` VALUES ('KW', 'Kuwait', '科威特');
INSERT INTO `tblCountryAbbr` VALUES ('KY', 'Cayman Islands', '开曼群岛');
INSERT INTO `tblCountryAbbr` VALUES ('KZ', 'Kazakstan', '哈萨克斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('LA', 'Laos', '老挝');
INSERT INTO `tblCountryAbbr` VALUES ('LB', 'Lebanon', '黎巴嫩');
INSERT INTO `tblCountryAbbr` VALUES ('LC', 'St.Lucia', '圣卢西亚');
INSERT INTO `tblCountryAbbr` VALUES ('LI', 'Liechtenstein', '列支敦士登');
INSERT INTO `tblCountryAbbr` VALUES ('LK', 'Sri Lanka', '斯里兰卡');
INSERT INTO `tblCountryAbbr` VALUES ('LR', 'Liberia', '利比里亚');
INSERT INTO `tblCountryAbbr` VALUES ('LS', 'Lesotho', '莱索托');
INSERT INTO `tblCountryAbbr` VALUES ('LT', 'Lithuania', '立陶宛');
INSERT INTO `tblCountryAbbr` VALUES ('LU', 'Luxembourg', '卢森堡');
INSERT INTO `tblCountryAbbr` VALUES ('LV', 'Latvia', '拉脱维亚');
INSERT INTO `tblCountryAbbr` VALUES ('LY', 'Libya', '利比亚');
INSERT INTO `tblCountryAbbr` VALUES ('MA', 'Morocco', '摩洛哥');
INSERT INTO `tblCountryAbbr` VALUES ('MC', 'Monaco', '摩纳哥');
INSERT INTO `tblCountryAbbr` VALUES ('MD', 'Moldova, Republic of', '摩尔多瓦');
INSERT INTO `tblCountryAbbr` VALUES ('ME', 'Montenegro', '黑山共和国');
INSERT INTO `tblCountryAbbr` VALUES ('MF', 'Saint Martin', '圣马丁');
INSERT INTO `tblCountryAbbr` VALUES ('MG', 'Madagascar', '马达加斯加');
INSERT INTO `tblCountryAbbr` VALUES ('MH', 'Marshall Islands', '马绍尔群岛');
INSERT INTO `tblCountryAbbr` VALUES ('MK', 'Macedonia', '马其顿');
INSERT INTO `tblCountryAbbr` VALUES ('ML', 'Mali', '马里');
INSERT INTO `tblCountryAbbr` VALUES ('MM', 'Burma', '缅甸');
INSERT INTO `tblCountryAbbr` VALUES ('MN', 'Mongolia', '蒙古');
INSERT INTO `tblCountryAbbr` VALUES ('MO', 'Macao', '澳门');
INSERT INTO `tblCountryAbbr` VALUES ('MP', 'Northern Mariana Islands', '北马里亚纳群岛');
INSERT INTO `tblCountryAbbr` VALUES ('MQ', 'Martinique', '马提尼克');
INSERT INTO `tblCountryAbbr` VALUES ('MR', 'Mauritania', '毛里塔尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('MS', 'Montserrat Is', '蒙特塞拉特岛');
INSERT INTO `tblCountryAbbr` VALUES ('MT', 'Malta', '马耳他');
INSERT INTO `tblCountryAbbr` VALUES ('MU', 'Mauritius', '毛里求斯');
INSERT INTO `tblCountryAbbr` VALUES ('MV', 'Maldives', '马尔代夫');
INSERT INTO `tblCountryAbbr` VALUES ('MW', 'Malawi', '马拉维');
INSERT INTO `tblCountryAbbr` VALUES ('MX', 'Mexico', '墨西哥');
INSERT INTO `tblCountryAbbr` VALUES ('MY', 'Malaysia', '马来西亚');
INSERT INTO `tblCountryAbbr` VALUES ('MZ', 'Mozambique', '莫桑比克');
INSERT INTO `tblCountryAbbr` VALUES ('NA', 'Namibia', '纳米比亚');
INSERT INTO `tblCountryAbbr` VALUES ('NC', 'New Caledonia', '新喀里多尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('NE', 'Niger', '尼日尔');
INSERT INTO `tblCountryAbbr` VALUES ('NF', 'Norfolk Island', '诺福克岛');
INSERT INTO `tblCountryAbbr` VALUES ('NG', 'Nigeria', '尼日利亚');
INSERT INTO `tblCountryAbbr` VALUES ('NI', 'Nicaragua', '尼加拉瓜');
INSERT INTO `tblCountryAbbr` VALUES ('NL', 'Netherlands', '荷兰');
INSERT INTO `tblCountryAbbr` VALUES ('NO', 'Norway', '挪威');
INSERT INTO `tblCountryAbbr` VALUES ('NP', 'Nepal', '尼泊尔');
INSERT INTO `tblCountryAbbr` VALUES ('NR', 'Nauru', '瑙鲁');
INSERT INTO `tblCountryAbbr` VALUES ('NU', 'Niue', '纽埃');
INSERT INTO `tblCountryAbbr` VALUES ('NZ', 'New Zealand', '新西兰');
INSERT INTO `tblCountryAbbr` VALUES ('OM', 'Oman', '阿曼');
INSERT INTO `tblCountryAbbr` VALUES ('PA', 'Panama', '巴拿马');
INSERT INTO `tblCountryAbbr` VALUES ('PE', 'Peru', '秘鲁');
INSERT INTO `tblCountryAbbr` VALUES ('PF', 'French Polynesia', '法属玻利尼西亚');
INSERT INTO `tblCountryAbbr` VALUES ('PG', 'Papua New Cuinea', '巴布亚新几内亚');
INSERT INTO `tblCountryAbbr` VALUES ('PH', 'Philippines', '菲律宾');
INSERT INTO `tblCountryAbbr` VALUES ('PK', 'Pakistan', '巴基斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('PL', 'Poland', '波兰');
INSERT INTO `tblCountryAbbr` VALUES ('PM', 'Saint Pierre And Miquelon', '圣皮埃尔和密克隆');
INSERT INTO `tblCountryAbbr` VALUES ('PN', 'Pitcairn', '皮特凯恩');
INSERT INTO `tblCountryAbbr` VALUES ('PR', 'Puerto Rico', '波多黎各');
INSERT INTO `tblCountryAbbr` VALUES ('PS', 'Palestinian Territory', '巴勒斯坦领土');
INSERT INTO `tblCountryAbbr` VALUES ('PT', 'Portugal', '葡萄牙');
INSERT INTO `tblCountryAbbr` VALUES ('PY', 'Paraguay', '巴拉圭');
INSERT INTO `tblCountryAbbr` VALUES ('QA', 'Qatar', '卡塔尔');
INSERT INTO `tblCountryAbbr` VALUES ('RE', 'Réunion', '留尼旺');
INSERT INTO `tblCountryAbbr` VALUES ('RO', 'Romania', '罗马尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('RS', 'Serbia', '塞尔维亚');
INSERT INTO `tblCountryAbbr` VALUES ('RU', 'Russia', '俄罗斯');
INSERT INTO `tblCountryAbbr` VALUES ('RW', 'Rwanda', '卢旺达');
INSERT INTO `tblCountryAbbr` VALUES ('SA', 'Saudi Arabia', '沙特阿拉伯');
INSERT INTO `tblCountryAbbr` VALUES ('SB', 'Solomon Is', '所罗门群岛');
INSERT INTO `tblCountryAbbr` VALUES ('SC', 'Seychelles', '塞舌尔');
INSERT INTO `tblCountryAbbr` VALUES ('SD', 'Sudan', '苏丹');
INSERT INTO `tblCountryAbbr` VALUES ('SE', 'Sweden', '瑞典');
INSERT INTO `tblCountryAbbr` VALUES ('SG', 'Singapore', '新加坡');
INSERT INTO `tblCountryAbbr` VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha', '圣赫勒拿岛，阿森松岛和特里斯坦 - 达库尼亚群岛');
INSERT INTO `tblCountryAbbr` VALUES ('SI', 'Slovenia', '斯洛文尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('SJ', 'Svalbard and Jan Mayen', '斯瓦尔巴群岛和扬马延');
INSERT INTO `tblCountryAbbr` VALUES ('SK', 'Slovakia', '斯洛伐克');
INSERT INTO `tblCountryAbbr` VALUES ('SL', 'Sierra Leone', '塞拉利昂');
INSERT INTO `tblCountryAbbr` VALUES ('SM', 'San Marino', '圣马力诺');
INSERT INTO `tblCountryAbbr` VALUES ('SN', 'Senegal', '塞内加尔');
INSERT INTO `tblCountryAbbr` VALUES ('SO', 'Somali', '索马里');
INSERT INTO `tblCountryAbbr` VALUES ('SR', 'Suriname', '苏里南');
INSERT INTO `tblCountryAbbr` VALUES ('SS', 'South Sudan', '南苏丹');
INSERT INTO `tblCountryAbbr` VALUES ('ST', 'Sao Tome and Principe', '圣多美和普林西比');
INSERT INTO `tblCountryAbbr` VALUES ('SV', 'EI Salvador', '萨尔瓦多');
INSERT INTO `tblCountryAbbr` VALUES ('SX', 'Sint Maarten (dutch Part)', '圣马丁岛（荷兰部分）');
INSERT INTO `tblCountryAbbr` VALUES ('SY', 'Syria', '叙利亚');
INSERT INTO `tblCountryAbbr` VALUES ('SZ', 'Swaziland', '斯威士兰');
INSERT INTO `tblCountryAbbr` VALUES ('TC', 'Turks And Caicos Islands', '特克斯和凯科斯群岛');
INSERT INTO `tblCountryAbbr` VALUES ('TD', 'Chad', '乍得');
INSERT INTO `tblCountryAbbr` VALUES ('TF', 'French Southern Territories', '法国南部领土');
INSERT INTO `tblCountryAbbr` VALUES ('TG', 'Togo', '多哥');
INSERT INTO `tblCountryAbbr` VALUES ('TH', 'Thailand', '泰国');
INSERT INTO `tblCountryAbbr` VALUES ('TJ', 'Tajikstan', '塔吉克斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('TK', 'Tokelau', '托克劳');
INSERT INTO `tblCountryAbbr` VALUES ('TL', 'Timor-leste', '东帝汶');
INSERT INTO `tblCountryAbbr` VALUES ('TM', 'Turkmenistan', '土库曼斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('TN', 'Tunisia', '突尼斯');
INSERT INTO `tblCountryAbbr` VALUES ('TO', 'Tonga', '汤加');
INSERT INTO `tblCountryAbbr` VALUES ('TR', 'Turkey', '土耳其');
INSERT INTO `tblCountryAbbr` VALUES ('TT', 'Trinidad and Tobago', '特立尼达和多巴哥');
INSERT INTO `tblCountryAbbr` VALUES ('TV', 'Tuvalu', '图瓦卢');
INSERT INTO `tblCountryAbbr` VALUES ('TW', 'Taiwan', '台湾省');
INSERT INTO `tblCountryAbbr` VALUES ('TZ', 'Tanzania', '坦桑尼亚');
INSERT INTO `tblCountryAbbr` VALUES ('UA', 'Ukraine', '乌克兰');
INSERT INTO `tblCountryAbbr` VALUES ('UG', 'Uganda', '乌干达');
INSERT INTO `tblCountryAbbr` VALUES ('UM', 'United States Minor Outlying Islands', '美国本土外小岛屿');
INSERT INTO `tblCountryAbbr` VALUES ('US', 'United States of America', '美国');
INSERT INTO `tblCountryAbbr` VALUES ('UY', 'Uruguay', '乌拉圭');
INSERT INTO `tblCountryAbbr` VALUES ('UZ', 'Uzbekistan', '乌兹别克斯坦');
INSERT INTO `tblCountryAbbr` VALUES ('VA', 'Holy See (vatican City State)', '教廷（梵蒂冈城国）');
INSERT INTO `tblCountryAbbr` VALUES ('VC', 'Saint Vincent', '圣文森特岛');
INSERT INTO `tblCountryAbbr` VALUES ('VE', 'Venezuela', '委内瑞拉');
INSERT INTO `tblCountryAbbr` VALUES ('VG', 'Virgin Islands, British', '维尔京群岛，英属');
INSERT INTO `tblCountryAbbr` VALUES ('VI', 'Virgin Islands, U.s.', '英属维尔京群岛，美国');
INSERT INTO `tblCountryAbbr` VALUES ('VN', 'Vietnam', '越南');
INSERT INTO `tblCountryAbbr` VALUES ('VU', 'Vanuatu', '瓦努阿图');
INSERT INTO `tblCountryAbbr` VALUES ('WF', 'Wallis And Futuna', '瓦利斯群岛和富图纳群岛');
INSERT INTO `tblCountryAbbr` VALUES ('WS', 'Samoa', '萨摩亚');
INSERT INTO `tblCountryAbbr` VALUES ('XK', 'Serbia', '塞尔维亚');
INSERT INTO `tblCountryAbbr` VALUES ('YE', 'Yemen', '也门');
INSERT INTO `tblCountryAbbr` VALUES ('YT', 'Mayotte', '马约特');
INSERT INTO `tblCountryAbbr` VALUES ('ZA', 'South Africa', '南非');
INSERT INTO `tblCountryAbbr` VALUES ('ZM', 'Zambia', '赞比亚');
INSERT INTO `tblCountryAbbr` VALUES ('ZW', 'Zimbabwe', '津巴布韦');
